# Generated by Django 4.2.3 on 2023-09-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_businessprofile_logo_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
